version: '3'
services:
        php:
            build: php
        volumes:
            - ./html:/var/www/html
        ports:
            - 7890:80

        mysql:
            image: mysql:5.7
            environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: db
                MYSQL_USER: user
                MYSQL_PASSWORD: password
            volumes:
                - ./mysql:/var/lib/mysql
            ports:
                - 3306:3306